name: Compiler Test

on: [push]

jobs:
  compiler_test:
    name: Compiler Test
    runs-on: [self-hosted, sysy-runner]
    steps:
      - uses: actions/checkout@v2
      - name: copy source
        run: |
          rm -rf /home/git/compiler/src/*
          cp -r -t /home/git/compiler/src/ src/*
      - name: run test script
        run: |
          python -u /app/main.py ~/configs/config-${{ github.ref_name }}.json
      - name: find test artifact
        run: |
          cd /home/git/logs
          ARTIFACT_PATH=$(realpath $(ls | sort -r | head -n 1))
          echo ${ARTIFACT_PATH}
          echo "ARTIFACT_PATH=${ARTIFACT_PATH}" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: result_${{ github.run_id }}
          path: ${{ env.ARTIFACT_PATH }}/result*
